### ISSUE TITLE
How to set zoom size?

### ISSUE THREAD

**Issue by Raserad** [lvnkmn/Zoomy#63]
Hi, when i use instagram behaviour my pinch to zoom is too small. Can i increase it? And when i zoom my image, my uitableview scroll with my fingers. How to solve it?

**Comment by lvnkmn** [comment]
Hi Raserad,

**Increase zoom**
By default, you can zoom in to twice the image size, if you want to be able to zoom to 5 times the original image's size, try this:
`addZoombehavior(for: imageView, settings: Settings.instaZoomSettings.with(maximumZoomScale: 5))`

another way to solve this, is by using higher resolution images on the UIImageView that you want to soon on.

**Prevent scrolling**
In order to prevent scrolling, make sure the viewcontroller you're zooming in conforms to `Zoomy.Delegate` in implement the following methods as follows:

    func didBeginPresentingOverlay(for imageView: UIImageView) {
        scrollView.isScrollEnabled = false
    }
    
    func didEndPresentingOverlay(for imageView: UIImageView) {
         scrollView.isScrollEnabled = true
    }

You can see an example of this [here](https://github.com/lvnkmn/Zoomy/blob/develop/Example/Zoomy/StackViewImagesViewController.swift)

Please let me know if this solves your problems 🙂

**Comment by Raserad** [comment]
Thank you very much) for your big work) Your library is very good for me))
