### ISSUE TITLE
Please update podspec file

### ISSUE THREAD

**Issue by hanawat** [lvnkmn/Zoomy#84]
Are you no longer using fastlane releases?
The version of cocoapods is out of date because podspec is not updated.

**Comment by lvnkmn** [comment]
Sorry Cocoapods hasn't been supported for a while now. This is (admittedly silently) reflected in the readme in the installation part.

The reason that it is still in the fastfile. Is that since swift package manager, there hasn't need for release automation anymore since all is needed is a git tag, to be honest I'm not even sure if the CI/CD is still running. I'll remove all pod related files and references to make it more clear.

Zoomy development is really sleeping, feel free to fork of you'd like to continue the use of cocoapods. Otherwise consider switching to SPM (for this dependency or all).

**Comment by hanawat** [comment]
I understand. Thanks for the reply!

**Comment by lvnkmn** [comment]
You're welcome!
